version: "3.2"

services:
  postgresql:
    image: postgres:11.1
    environment:
      POSTGRES_DB: architector
      POSTGRES_USER: architector
      POSTGRES_PASSWORD: architector
    ports:
    - 5432:5432
    volumes:
    - ./postgres-db-architector:/var/lib/postgresql/data

  service:
    image: valeriyknyazhev/architector:2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/architector
    deploy:
      replicas: 1
    ports:
    - 80:8080
    depends_on:
    - postgresql