version: "3.2"

services:
  postgresql:
    image: postgres:11.1
    environment:
      POSTGRES_DB: architector
      POSTGRES_USER: architector
      POSTGRES_PASSWORD: architector
    ports:
    - 5432:5432
