server.port: 8080

spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    temp.use_jdbc_metadata_defaults: false

spring.liquibase.change-log: classpath:/db/db.changelog-master.xml

spring.datasource:
  url: jdbc:postgresql://localhost:5432/architector
  username: architector
  password: architector

spring.session:
  store-type: jdbc
  jdbc:
    table-name: spring_session

server.servlet.session:
  timeout: 600
  cookie:
    http-only: true
    secure: true
    max-age: 600

security.jwt.token:
  secret-key: |
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDmvEOnDmyYWL5crOUutktaX1SL
    fgOklZpYGljihwSQJrqCvcU3Av0KDymggVSYlEc7+LjbePsa7vPSvCpszL6yNIPQ
    UTt/yhJ9Jfur1e3PVcpeelO4UPeZFzYHo9t+WMuToWLq/NL3NnW90ECZgIxahFPl
    6EbfMx3DZLBbFJqFHwIDAQAB
  expire-length: 7200000