server.port: 8080

spring.jpa:
  hibernate:
    ddl-auto: create-drop
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    temp.use_jdbc_metadata_defaults: false

spring.datasource:
  url: jdbc:postgresql://localhost:5432/architector
  username: architector
  password: architector